### ISSUE TITLE
这AI耍无赖呀。。。

### ISSUE THREAD

**Issue by jx3fans** [lihongxun945/gobang#10]
<img width="499" alt="wx20180303-114439 2x" src="https://user-images.githubusercontent.com/870076/36930270-5a236afa-1ed8-11e8-9488-1819be5613a7.png">
明明白色的先成5个的，结果AI耍赖说自己黑的赢了。。。

**Comment by ChenRenault** [comment]
![image](https://user-images.githubusercontent.com/8744395/41414407-760a7ff6-7018-11e8-8a90-95ed55686844.png)
我也遇到相同的问题.
