### ISSUE TITLE
算了7分钟

### ISSUE THREAD

**Issue by codesboy** [lihongxun945/gobang#12]
![qq 20180409175742](https://user-images.githubusercontent.com/9047357/38491804-88c4c02a-3c1f-11e8-9625-ddc8adf1a6fb.png)

**Comment by lihongxun945** [comment]
@codesboy @tangyan02 最近更新了，速度有了非常大幅度的提升，在我的iphone7, safari 上，平均每步时间不超过2秒。感谢反馈~
