### ISSUE TITLE
第一次用，出来那个激萌动图吓我一跳

### ISSUE THREAD

**Issue by sayelaoda** [lihongxun945/gobang#17]

**Comment by sayelaoda** [comment]
![image](https://user-images.githubusercontent.com/35267603/49081934-4b22a780-f283-11e8-9d64-b6efdf922464.png)
不用神经网络训练感觉没有变数啊……

**Comment by venn29** [comment]
不用神经网络训练当然没有变数啦，传统的棋类AI都这样，毕竟从评估到递归到递归和剪枝的顺序都是一样的
